// let first_name = "mohammadreza";
// let age = 23;
// let isMale = true;
// // first_name = 26
// first_name = "alireza";
// // age = "slam";
// age = 33;
// const circ = (diameter: number) => {
//   return Math.PI * diameter;
// };
// console.log(circ(10));
// let names = ["mahdi", "bahram"];
// // names[1] = 23;
// // names.push(26);
// names.push("mohammadreza");
// names[4] = "aborooye";
// let mixed = ["", 10];
// mixed[1] = "anbop";
// mixed[2] = 15;
// mixed[4] = "man";
// console.log(mixed);
var fname;
var age;
fname = "ali";
age = 46;
var numbers = [];
numbers.push("mah");
numbers.push(12);
// numbers.push();
console.log(numbers);
var person = { name: "ali", id: 16 };
